# Generated by Django 5.0.1 on 2024-01-25 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='cotegory',
            new_name='category',
        ),
    ]
